### PR TITLE
✨🚧 [WIP] Save the filename of the uploaded Diagram to the ProcessEngine

### LINKED ISSUE #1060: 🐛Process name used instead of file name when deploying
#### Describe your issue

When uploading a diagram to a PE the process name is used instead of the file name.
This leads to confusion since the file name can be hugely different to the process name.
Then you got the same diagram with different names.
And what makes this even worse we are overwriting a diagram on the PE by deploying.
That diagram on the PE sometimes does not have the name as the file but gets overwritten when you deploy it.

Relates to #1050 

#### How can others reproduce the issue?

- Create a diagram called `test`.
- Edit the diagram and name the process `test2`.
- Deploy the diagram.
- See how it gets displayed with `test` in the solution section of Solution Explorer and `test2` on the PE section.

#### Possible solution

Take the file name to upload the diagram to the PE.

#### What's your setup

- BPMN-Studio Version (`4.7.0`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by robpal94**
---

**Changes:**

1. Upload the Filename of a diagram to the ProcessEngine

**Issues:**

Closes #1060

PR: #1064 

---

See the [examples](#example) for inspiration.

## How can others test the changes?

> Describe how others can test your changes (you can remove this section for typo fixes etc.)

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

**Comment by robpal94** [comment]
This should be kept on hold until we discussed how we work around the wrong backend behavior as described in the referenced issue.

**Comment by alexanderkasten** [comment]
@robpal94 Where can I find the `referenced` issue?

**Comment by alexanderkasten** [comment]
@robpal94 Where can I find the `referenced` issue?

**Comment by robpal94** [comment]
Closing this since the usage of the _name_ field in the ProcessEngine has yet to be defined properly.

**Pull request closed without merging**
