### PR TITLE
Mark primary buttons with btn-primary

### LINKED ISSUE #334: UI allgemein: Alle Buttons haben Farben - wenn alle Elemente auffällig sind, fällt keines auf
**Beschreibe das Problem:**

Sehr anschaulich im Settings-Dialog: Beide Buttons haben Farben. 

Der eine Button speichert den Dialog. Seine Auswirkungen können sehr schwerwiegend sein, weil er die Anbindung an die ProcessEngine umkonfiguriert. Er ist grün.

Der Button, der den Dialog abbricht und dessen Betätigung keinerlei Auswirkungen auf den Status quo hat, ist rot.

Wenn alle Kontrollelemente einer Benutzeroberfläche auffällig, farbig und evtl. noch mit Icons versehen sind, dann fällt keines von ihnen mehr auf.

image

### PR DESCRIPTION
**Pull request by rrrene**
## Changes

1. Primary buttons are now marked by color

## Issues

Closes #334 

PR: #1504

## How to test the changes

image

### CODE REVIEW

**Comment by rrrene** [comment]
Closes #334

**Comment by SteffenKn** [comment]
@alexanderkasten This is because the button is disabled

**Comment by alexanderkasten** [comment]
> @alexanderkasten This is because the button is disabled

IMO a hover effect on disabled buttons is not useful.

**Comment by rrrene** [comment]
@alexanderkasten re-review plz!

**Pull request merged**
